### ISSUE TITLE
slow loading

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/showcase#140]
https://desmart.com/blog/react-is-slow-oh-wait-tips-on-how-to-optimize-react-apps-performance-1
https://hackernoon.com/improving-first-time-load-of-a-production-react-app-part-1-of-2-e7494a7c7ab0
https://medium.com/myheritage-engineering/how-to-greatly-improve-your-react-app-performance-e70f7cbbb5f6
https://marmelab.com/blog/2017/02/06/react-is-slow-react-is-fast.html

**Comment by vadim9999** [comment]
I tried this method in component Cell 
```
shouldComponentUpdate(nextProps, nextState) {
  if (this.props.name !== nextProps.name) {
    console.log("Name **********************");
        return true;
    }

      console.log("False ****************************");
      return false;
    }
```
After this when I open a tile it's empty also I have installed "why-did-you-update" that display re-render when loading home it`s ~ 451 re-render when open a tile ~ 1117

**Comment by atherdon** [comment]
wow thisi our candidate!

**Comment by vadim9999** [comment]
ok, it's working PureComponent and shouldComponentUpdate()
I just needed more learn

**Comment by atherdon** [comment]
cool! optimization is an important thing - i like that you learning it
also, you can apply your debug to this samples:
https://codesandbox.io/embed/0582jolnl
https://codesandbox.io/embed/z6ly40071p

i just want to eliminate the possibility that this is an issue, related to package that we're using - because if this is their issue - we can not only solve our trouble - but also contribute to other project

**Comment by atherdon** [comment]
did we solve this issue, right? at my side - it works better

**Comment by vadim9999** [comment]
yes
