### ISSUE TITLE
move our items loop into a separated file and create a separated components for it.

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/showcase#16]
it'll make our code cleaner.

This is should be 3 components. One related to list of departments,
second is department info(id, department name, list of ingredients), third is list of ingredients

**Comment by atherdon** [comment]
@vadim9999 each of this components should have this structure:
'/src/components/ComponentName/ComponentName.js'
+
'/src/components/ComponentName/ComponentName.test.js'
'/src/components/ComponentName/ComponentName.scss'

**Comment by vadim9999** [comment]
@atherdon should I rename files in folder component?
DepartmentInfo.js	
Ingredients.js	
RenderGrocery.js

**Comment by atherdon** [comment]
keep them as it is for now. I'm ok with this names.
Our main goal, for now, is to have a sanbox where we can work on this separated static thing.
later, when we'll add this functionality into our main project - we'll discuss names/structure, etc

Btw, i pushed some updates, please fetch them from main repo.
