### ISSUE TITLE
good api example

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/showcase#234]
right now i launch our project locally, and i don't have server running - homepage didn't show anything at this moment. i assume that we need to cover this case too: if api didn't return to us anything - we should display some sort of warning message.

If you want to make it more cool - buzz me and i'll show you how to create a cool NO DATA component

**Comment by vadim9999** [comment]
I want to make more cool no data component

**Comment by atherdon** [comment]
Ok, good to know. but it will require a combination of things.
First of all - i think we woudln't be able to test it without connection to fake-api(where we have an error). But, it can be a good case for showing the reason of why we need to implement this scenario. Because it's an exact situation were server is not available...

---

1. I find this page: https://ant-design.gitee.io/components/list/#components-list-demo-loadmore
and we have a ListWrapper component, that actually 'copy-paste' from this kind of examples.
2. https://ant-design.gitee.io/components/empty/ is a component, that we're will display when we don't have information.

And I moved a major part of these components into this few repositories: 
https://github.com/GroceriStar/cards-wrapper-component
https://github.com/GroceriStar/antd-showcase-components

I can give you more information, but i want you to research it more, because it will help you later.

**Comment by vadim9999** [comment]
this two repos are just library
https://github.com/GroceriStar/cards-wrapper-component
https://github.com/GroceriStar/antd-showcase-components
I can't debug it. I will adding in showcase

**Comment by atherdon** [comment]
we have a sandbox projects, where you can debug. but yeah, you need to connect them to react project and then adjust code at modules, if needed. Btw, keep in mind that some of not finished components at that files has connection to selectors, and this is not ok. we need to pass data from the parent. But i'm sure you'll be able to handle it

**Comment by vadim9999** [comment]
We can close it?

**Comment by atherdon** [comment]
did we finish it?

**Comment by atherdon** [comment]
because i didn't see it. but i may miss something easily

**Comment by vadim9999** [comment]
I have connect Empty component from  card-wrapper-component that will appear whe no connection to DB (fake-api) and spinning circle in opened title. Should it be somethin else?

**Comment by atherdon** [comment]
hold on, i'll grab latest changes from repo and will take a look. i think i
didn't do it quite a while ago. then i'll be able to answer to your
question.
Actually, as i don't setup my local server - it will be a perfect case to
test

**Comment by atherdon** [comment]
ok it works! awesome news.

**Comment by atherdon** [comment]
@vadim9999 I think we need the similar functionality at recipe-antd and at antd-showcase project. Can you move this code to that projects too?

**Comment by vadim9999** [comment]
ok
